# -*- coding: utf-8 -*-
"""grade_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hY6EQk6zjzM4j-No0_SZmeg-l0FYeA7a
"""

name = input("Enter student name: ")

marks = int(input("Enter marks (0-100): "))

while marks < 0 or marks > 100:
    print("Invalid marks! Please enter marks between 0 and 100.")
    marks = int(input("Enter marks (0-100): "))

def calculate_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    elif marks >= 60:
        return "D"
    else:
        return "F"

def grade_message(grade):
    if grade == "A":
        return "Excellent work! "
    elif grade == "B":
        return "Very Good! Keep it up! "
    elif grade == "C":
        return "Good effort! You can do better "
    elif grade == "D":
        return "Needs improvement. Don’t give up!"
    else:
        return "Better luck next time. Keep trying "

grade = calculate_grade(marks)
message = grade_message(grade)

print("\n📊 RESULT")
print("Student Name:", name)
print("Marks:", marks, "/100")
print("Grade:", grade)
print("Message:", message)

name = input("Enter student name: ")

marks = int(input("Enter marks (0-100): "))

while marks < 0 or marks > 100:
    print("Invalid marks! Please enter marks between 0 and 100.")
    marks = int(input("Enter marks (0-100): "))

def calculate_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    elif marks >= 60:
        return "D"
    else:
        return "F"
def grade_message(grade):
    if grade == "A":
        return "Excellent work! "
    elif grade == "B":
        return "Very Good! Keep it up! "
    elif grade == "C":
        return "Good effort! You can do better "
    elif grade == "D":
        return "Needs improvement. Don’t give up"
    else:
        return "Better luck next time. Keep trying "

grade = calculate_grade(marks)
message = grade_message(grade)

print("\n📊 RESULT")
print("Student Name:", name)
print("Marks:", marks, "/100")
print("Grade:", grade)
print("Message:", message)