# -*- coding: utf-8 -*-
"""personal_intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TB5dxM71r6iCUAq3iNREJYFVAijumOpc
"""

print("Hello, World!")

name = "wafa"
age = 20
city = "pune"

print(name)
print(age)
print(city)

a = 10
b = 5

print(a + b)
print(a - b)
print(a * b)
print(a / b)

first_name = "Alex"
hobby = "coding"

sentence = first_name + " loves " + hobby
print(sentence)

foods = ["Pizza", "Burger", "Pasta"]

print(foods[0])
print(foods[1])

print("Hello, World!")

name = input("What is your name? ")
age = input("How old are you? ")
city = input("Which city are you from? ")

print(f"Welcome {name}!")
print(f"You are {age} years old and from {city}.")

hobby = input("What is your favorite hobby? ")